version: '2'

services:
  rekog_mean:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/project
    stdin_open: true
  mongo:  
    image: mongo
    ports:
      - "27017:27017"
