version: '2'

services:
  rekog_mean:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/project
    working_dir: /project
    stdin_open: true
